spring:
  datasource:
    username: ${DB_USER_NAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQLDialect

security:
  jwt:
    header: ${JWT_AUTH:Authorization}
    secret: ${JWT_SECRET:superCoding}
    token-validity-in-seconds: 604800

#aws:
#  accessKeyId: ${AWS_ACCESS_KEY}
#  secretKey: ${AWS_SECRET_KEY}
#  region: ${AWS_REGION}
#  s3:
#    bucketName: ${AWS_BUCKET}

logging:
  level:
    org.springframework.security: DEBUG
