spring:
  profiles:
    active: local
    include: oauth
  datasource:
    username: ${DB_NAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      enabled: true
      max-file-size: 300MB
      max-request-size: 300MB
  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

security:
  jwt:
    header: ${JWT_AUTH:Authorization}
    secret: ${JWT_SECRET:dlrjsmstlzmfltzldidkdkdkdfdfdddddddf}
    token-validity-in-seconds: 604800

cloud:
  aws:
    s3:
      bucket: ${bucket}
    credentials:
      access-key: ${access-key}
      secret-key: ${secret-key}
    region:
      static: ap-northeast-2

logging:
  level:
    org.springframework.security: DEBUG
